### [객체지향] Numpy (2) : 연산 심화, 인덱싱과 슬라이싱
[블로그 주소](https://mungdo-log.tistory.com/354)

**행렬 연산**

In [10]:
import numpy as np
# 여러 변수 출력 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [11]:
A = np.array([[1,2],[3,4]])
B = np.array([[2,1],[4,3]])
A
B

array([[1, 2],
       [3, 4]])

array([[2, 1],
       [4, 3]])

In [8]:
# 행렬 곱
A.dot(B) # np.dot(A,B)

array([[10,  7],
       [22, 15]])

In [9]:
# 전치 행렬
A.transpose()

array([[1, 3],
       [2, 4]])

In [12]:
# 역행렬
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [15]:
# 행렬식
np.linalg.det(A)
np.linalg.det(B)

-2.0000000000000004

2.0

---

### 배열의 인덱싱과 슬라이싱

**인덱싱**

In [30]:
import random

np.random.seed(0)
arr1 = np.array(np.random.randint(0,10,size=10))
arr1

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [32]:
arr1[9]
arr1[0]

4

5

In [35]:
arr1[[9,0]]

array([4, 5])

In [37]:
arr2 = arr1.reshape((2,5))
arr2

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4]])

In [39]:
arr2[1,2]

5

In [42]:
arr2[[0,1],[2,4]] # (0,2) = 3, (1,4) = 4

array([3, 4])

In [44]:
arr2[arr2 > 4]

array([5, 7, 9, 5])

In [55]:
arr2[0][:3]

array([5, 0, 3])

In [56]:
arr2[0:2][1:3]

array([[9, 3, 5, 2, 4]])

In [57]:
arr2[0:2][2]

IndexError: index 2 is out of bounds for axis 0 with size 2