In [22]:
import numpy as np

In [23]:
a = np.array([[5, 7, -5, 100, 73], [35, 23, 4, 190, 33], [49, 85, 662, 39, 81], [124, -59, 86, 46, 52], [27, 7, 8, 33, -56]])

In [24]:
for i in range(5):
    for j in range(5):
        if a[i][j] < 0 : a[i][j] = 0
        if a[i][j] > 100 : a[i][j] %= 100

print(a)

[[  5   7   0 100  73]
 [ 35  23   4  90  33]
 [ 49  85  62  39  81]
 [ 24   0  86  46  52]
 [ 27   7   8  33   0]]


In [25]:
maxA = 0
for i in range(4):
    for j in range(4):
        sumA = a[i][j] + a[i+1][j] + a[i][j+1] + a[i+1][j+1]
        # print(f'i: {i}, j: {j}, sum: {sumA}')
        if maxA < sumA : maxA = sumA
        # print(f'maxA : {maxA}')

print(maxA)

296


In [26]:
def findArraySumMax(array):
    
    for i in range(5):
        for j in range(5):
            if array[i][j] < 0 : array[i][j] = 0
            if array[i][j] > 100 : array[i][j] %= 100

    maxA = 0
    for i in range(4):
        for j in range(4):
            sumA = array[i][j] + array[i+1][j] + array[i][j+1] + array[i+1][j+1]
            # print(f'i: {i}, j: {j}, sum: {sumA}')
            if maxA < sumA : maxA = sumA
            # print(f'maxA : {maxA}')

    return maxA

In [27]:
a = np.array([[5, 7, -5, 100, 73], [35, 23, 4, 190, 33], [49, 85, 662, 39, 81], [124, -59, 86, 46, 52], [27, 7, 8, 33, -56]])
findArraySumMax(a)

296